<a href="https://colab.research.google.com/github/jyothijoo197-ui/datasciencelearning/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df =pd.read_excel("/content/drive/MyDrive/datasetsfordatasciencebytexl/student_dataset_20rows.xlsx")

In [2]:
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [3]:
# axis = 0 => removing rows
# axis = 1 => removing columns
df.drop("City", axis =1, inplace =True)

In [4]:
df

    Student_ID     Name  Age            Course  Marks
0          101      Ram   25            Pandas     90
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [5]:
df.drop(0, axis=0, inplace=True)

In [6]:
df

    Student_ID     Name  Age            Course  Marks
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [8]:
import pandas as pd
df =pd.read_excel("/content/drive/MyDrive/datasetsfordatasciencebytexl/student_dataset_20rows.xlsx")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [9]:
#selecting columns
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [10]:
df["Marks"]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [11]:
df["Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [12]:
df["City"]

0      Vijayawada
1       Hyderabad
2         Chennai
3       Bangalore
4          Mumbai
5           Delhi
6            Pune
7         Kolkata
8           Vizag
9        Tirupati
10       Warangal
11         Guntur
12        Nellore
13         Kadapa
14        Kurnool
15         Ongole
16    Rajahmundry
17          Eluru
18        Khammam
19      Nizamabad
Name: City, dtype: object

In [13]:
df[["Name", "Age"]]

       Name  Age
0       Ram   25
1      Ravi   23
2      Sita   21
3     Kiran   21
4       Anu   20
5     Rahul   22
6     Sneha   25
7     Arjun   22
8     Pooja   20
9    Vikram   20
10    Divya   23
11     Ajay   21
12  Keerthi   21
13   Nikhil   22
14    Meena   23
15      Sai   25
16  Lavanya   20
17    Rohit   23
18     Teja   25
19    Priya   22

In [14]:
df[["Name", "Age","City"]]

       Name  Age         City
0       Ram   25   Vijayawada
1      Ravi   23    Hyderabad
2      Sita   21      Chennai
3     Kiran   21    Bangalore
4       Anu   20       Mumbai
5     Rahul   22        Delhi
6     Sneha   25         Pune
7     Arjun   22      Kolkata
8     Pooja   20        Vizag
9    Vikram   20     Tirupati
10    Divya   23     Warangal
11     Ajay   21       Guntur
12  Keerthi   21      Nellore
13   Nikhil   22       Kadapa
14    Meena   23      Kurnool
15      Sai   25       Ongole
16  Lavanya   20  Rajahmundry
17    Rohit   23        Eluru
18     Teja   25      Khammam
19    Priya   22    Nizamabad

In [15]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [16]:
#selecting rows using iloc function
# iloc = integer location
df.iloc[0]

Student_ID           101
Name                 Ram
Age                   25
Course            Pandas
Marks                 90
City          Vijayawada
Name: 0, dtype: object

In [17]:
df.iloc[0:3]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [18]:
# selecting specific rows and columns
# df.iloc[rowselection, columnselection]
df.iloc[0:3, 0:3]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [19]:
df.iloc[0,0:3]

Student_ID    101
Name          Ram
Age            25
Name: 0, dtype: object

In [20]:
df.iloc[[0,1,2,3]]

   Student_ID   Name  Age        Course  Marks        City
0         101    Ram   25        Pandas     90  Vijayawada
1         102   Ravi   23         NumPy     81   Hyderabad
2         103   Sita   21        Python     80     Chennai
3         104  Kiran   21  Data Science     98   Bangalore

In [21]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [22]:
# suppose if i am accesing multiple rows
# in iloc function suppose my range is 0 to n > i will get output as o to n-1
# in loc function suppose my range is 0 to n > i will get output as 0 to n
#loc function if you want to access columns you have to use column names

In [23]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [24]:
df.loc[:,["Name", "Marks"]]

       Name  Marks
0       Ram     90
1      Ravi     81
2      Sita     80
3     Kiran     98
4       Anu     70
5     Rahul     82
6     Sneha     79
7     Arjun     70
8     Pooja     95
9    Vikram     72
10    Divya     94
11     Ajay     84
12  Keerthi     74
13   Nikhil     99
14    Meena     81
15      Sai     97
16  Lavanya     72
17    Rohit     70
18     Teja     90
19    Priya     78

In [25]:
df.loc[5:8, ["Name","Age", "City"]]

    Name  Age     City
5  Rahul   22    Delhi
6  Sneha   25     Pune
7  Arjun   22  Kolkata
8  Pooja   20    Vizag

In [26]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [27]:
# task1 : select Name Colum (loc, iloc, normal)
print(df["Name"])
print(df.loc[:,"Name"])
print(df.iloc[:,1])
# taks2: select Name, City Columns (loc, iloc, normal)
print(df[["Name", "City"]])
print(df.loc[:,["Name", "City"]])
print(df.iloc[:,[1,3]])
#task3: select first 3 rows(loc, iloc)
print(df.loc[0:2])
print(df.iloc[0:3])
# taks4: select first 3 rows and first 2 columns(loc, iloc)
print(df.loc[0:1,["Student_ID","Name"]])
print(df.iloc[0:2,0:2])
#task5 : select all rows and marks columns (loc, iloc)
print(df.loc[:,"Marks"])
print(df.iloc[:,4])

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad
       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad
       Name            Course
0       Ram            Pandas
1      Ravi             NumPy
2      Sita            Python
3     Kiran      Data Science
4       Anu            Pandas
5     Rahul               SQL
6     Sneha     Deep Learning
7     Arjun  Machine Learning
8     Pooja            Python
9    Vikram               SQL
10    Divya     Deep Learning
11     Ajay            Python
12  Keerthi             NumPy
13   Nikhil     Deep Learning
14    Meena                AI
15      Sai            Pandas
16  Lavanya                AI
17    Rohit            Python
18     Teja  Machine Learning
19    Priya               SQL
   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai
   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai
   Student_ID  Name
0         101   Ram
1         102  Ravi
   Student_ID  Name
0         101   Ram
1         102  Ravi
0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64
0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [28]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [29]:
df[df["Marks"]>80]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
8          109   Pooja   20            Python     95       Vizag
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [30]:
# filter marks greater than 80
df[df["Marks"]>80]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
8          109   Pooja   20            Python     95       Vizag
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [31]:
#marks less than 90
df[df["Marks"]<=90]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
14         115    Meena   23                AI     81      Kurnool
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [32]:
df[df["Age"]>=21]

    Student_ID     Name  Age            Course  Marks        City
0          101      Ram   25            Pandas     90  Vijayawada
1          102     Ravi   23             NumPy     81   Hyderabad
2          103     Sita   21            Python     80     Chennai
3          104    Kiran   21      Data Science     98   Bangalore
5          106    Rahul   22               SQL     82       Delhi
6          107    Sneha   25     Deep Learning     79        Pune
7          108    Arjun   22  Machine Learning     70     Kolkata
10         111    Divya   23     Deep Learning     94    Warangal
11         112     Ajay   21            Python     84      Guntur
12         113  Keerthi   21             NumPy     74     Nellore
13         114   Nikhil   22     Deep Learning     99      Kadapa
14         115    Meena   23                AI     81     Kurnool
15         116      Sai   25            Pandas     97      Ongole
17         118    Rohit   23            Python     70       Eluru
18         119     Teja   25  Machine Learning     90     Khammam
19         120    Priya   22               SQL     78   Nizamabad

In [33]:
df[df["City"] == "Vijayawada"]

   Student_ID Name  Age  Course  Marks        City
0         101  Ram   25  Pandas     90  Vijayawada

In [34]:
df[(df["Marks"]>80) & (df["Age"]>=21)]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [35]:
df[(df["Marks"]>80)  | (df["Age"]>=21)]

    Student_ID     Name  Age            Course  Marks        City
0          101      Ram   25            Pandas     90  Vijayawada
1          102     Ravi   23             NumPy     81   Hyderabad
2          103     Sita   21            Python     80     Chennai
3          104    Kiran   21      Data Science     98   Bangalore
5          106    Rahul   22               SQL     82       Delhi
6          107    Sneha   25     Deep Learning     79        Pune
7          108    Arjun   22  Machine Learning     70     Kolkata
8          109    Pooja   20            Python     95       Vizag
10         111    Divya   23     Deep Learning     94    Warangal
11         112     Ajay   21            Python     84      Guntur
12         113  Keerthi   21             NumPy     74     Nellore
13         114   Nikhil   22     Deep Learning     99      Kadapa
14         115    Meena   23                AI     81     Kurnool
15         116      Sai   25            Pandas     97      Ongole
17         118    Rohit   23            Python     70       Eluru
18         119     Teja   25  Machine Learning     90     Khammam
19         120    Priya   22               SQL     78   Nizamabad

In [36]:
df.loc[df["Marks"]>80 , ["Name" ,"Marks"]]

      Name  Marks
0      Ram     90
1     Ravi     81
3    Kiran     98
5    Rahul     82
8    Pooja     95
10   Divya     94
11    Ajay     84
13  Nikhil     99
14   Meena     81
15     Sai     97
18    Teja     90

In [37]:
#task1 filter students marks with less than 70
#taks2 filter stusents from banglore
#task3 students age less than 30
#task4 students with marks greater than 25 or age greater than 30
#taks5 show only name and age where city is chennai

In [38]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [39]:
# iloc()
# #rows, columns index values 0:3 =>0,1,2
# df.iloc[0:3] =>0,1,2
df.iloc[0:3,0:3]
# loc 0:3 => 0,1,2,3 =>0:2 =>0,1,2

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [40]:
df.loc[0:2,["Student_ID","Name", "Age"]]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [41]:
#task1 filter students marks with less than 70
#taks2 filter stusents from banglore
#task3 students age less than 30
#task4 students with marks greater than 25 or age greater than 30
#taks5 show only name and age where city is chennai

In [42]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [43]:
#task1 filter students marks with less than 90
df[df["Marks"]<90]

    Student_ID     Name  Age            Course  Marks         City
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
14         115    Meena   23                AI     81      Kurnool
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
19         120    Priya   22               SQL     78    Nizamabad

In [44]:
#taks2 filter stusents from banglore
df[df["City"] == "Bangalore"]

   Student_ID   Name  Age        Course  Marks       City
3         104  Kiran   21  Data Science     98  Bangalore

In [45]:
#task3 students age less than 30
df[df["Age"]<30]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [46]:
#task4 students with marks greater than 25 or age greater than 30
df[(df["Marks"]>25)|(df["Age"]<30)]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [47]:
#taks5 show only name and age where city is chennai
df.loc[df["City"]=="Chennai" , ["Name", "Age"]]

   Name  Age
2  Sita   21

In [48]:
#sorting :arranging data in a particular order
#usually ascending order, descending order
#df.sort_values(by="column name")

In [49]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [50]:
df.sort_values(by="Marks") #ascending order

    Student_ID     Name  Age            Course  Marks         City
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
6          107    Sneha   25     Deep Learning     79         Pune
2          103     Sita   21            Python     80      Chennai
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
5          106    Rahul   22               SQL     82        Delhi
11         112     Ajay   21            Python     84       Guntur
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
10         111    Divya   23     Deep Learning     94     Warangal
8          109    Pooja   20            Python     95        Vizag
15         116      Sai   25            Pandas     97       Ongole
3          104    Kiran   21      Data Science     98    Bangalore
13         114   Nikhil   22     Deep Learning     99       Kadapa

In [51]:
df.sort_values(by="Marks", ascending=False) #descending order

    Student_ID     Name  Age            Course  Marks         City
13         114   Nikhil   22     Deep Learning     99       Kadapa
3          104    Kiran   21      Data Science     98    Bangalore
15         116      Sai   25            Pandas     97       Ongole
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
11         112     Ajay   21            Python     84       Guntur
5          106    Rahul   22               SQL     82        Delhi
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
2          103     Sita   21            Python     80      Chennai
6          107    Sneha   25     Deep Learning     79         Pune
19         120    Priya   22               SQL     78    Nizamabad
12         113  Keerthi   21             NumPy     74      Nellore
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru

In [52]:
df.sort_values(by="City")

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal

In [53]:
df.sort_values(by=["City", "Marks"])

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal